# Advanced String Functions / Regex / Clause

## 1667. Fix Names in a Table

In [ ]:
SELECT user_id ,   
        CONCAT(UPPER(LEFT(name, 1)), LOWER(SUBSTRING(name, 2))) AS name
FROM Users
ORDER BY user_id;

## 1527. Patients With a Condition

In [ ]:
SELECT patient_id, patient_name, conditions
FROM Patients
WHERE conditions LIKE 'DIAB1%' OR conditions LIKE '% DIAB1%';

## 196. Delete Duplicate Emails

In [ ]:
DELETE P2
FROM Person as P1
INNER JOIN Person as P2
ON P1.email = P2.email
where p1.id<p2.id;

## 176. Second Highest Salary

In [ ]:
WITH RankEmployee AS(
    SELECT *, DENSE_RANK() OVER(ORDER BY salary DESC) AS ran
    FROM Employee
)

SELECT MAX(salary) as SecondHighestSalary
FROM RankEmployee
WHERE ran = 2;

## 1484. Group Sold Products By The Date

In [ ]:
SELECT sell_date, count(distinct product) as num_sold, GROUP_CONCAT(DISTINCT product ORDER BY product ASC SEPARATOR ',') as products
FROM Activities
GROUP BY sell_date
ORDER BY sell_date;

## 1327. List the Products Ordered in a Period

In [ ]:
SELECT p.product_name, sum(o.unit) as unit
FROM Products AS p
LEFT JOIN Orders as o
USING (product_id)
WHERE DATE_FORMAT(o.order_date, '%Y-%m') =  '2020-02'
GROUP BY product_id
HAVING SUM(o.unit) >= 100;

## 1517. Find Users With Valid E-Mails

In [ ]:
SELECT user_id, name, mail
FROM Users
WHERE REGEXP_LIKE(mail, '^[A-Za-z]+[A-Za-z0-9\_\.\-]*@leetcode\\.com$');